definitions:
  chai.Error:
    properties:
      error:
        type: string
      error_debug:
        type: string
      error_description:
        type: string
      status_code:
        type: integer
    type: object
  model.Account:
    properties:
      id:
        example: 1
        format: int64
        type: integer
      name:
        example: account name
        type: string
      some_number:
        example: 1234
        type: integer
      uuid:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/examples/attribute:
    get:
      description: attribute
      parameters:
      - description: string enums
        enum:
        - A
        - B
        - C
        in: query
        name: enumstring
        type: string
      - description: int enums
        enum:
        - 1
        - 2
        - 3
        in: query
        name: enumint
        type: integer
      - description: int enums
        enum:
        - 1.1
        - 1.2
        - 1.3
        in: query
        name: enumnumber
        type: number
      - description: string valid
        in: query
        maxLength: 10
        minLength: 5
        name: string
        type: string
      - description: int valid
        in: query
        maximum: 10
        minimum: 1
        name: int
        type: integer
      - default: A
        description: string default
        in: query
        name: default
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: answer
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
      summary: attribute example
      tags:
      - example
  /api/v1/examples/calc:
    get:
      parameters:
      - description: used for calc
        in: query
        name: val1
        required: true
        type: integer
      - description: used for calc
        in: query
        name: val2
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "203":
          description: ""
          schema:
            type: string
        "400":
          description: ""
          schema:
            type: string
        "404":
          description: ""
          schema:
            type: string
  /api/v1/examples/groups/{group_id}/accounts/{account_id}:
    get:
      description: path params
      parameters:
      - description: Group ID
        in: path
        name: group_id
        required: true
        type: integer
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            type: string
        "400":
          description: ""
          schema:
            type: string
        "404":
          description: ""
          schema:
            type: string
      summary: path params example
      tags:
      - example
  /api/v1/examples/header:
    get:
      description: custome header
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            type: string
        "400":
          description: ""
          schema:
            type: string
        "404":
          description: ""
          schema:
            type: string
      summary: custome header example
      tags:
      - example
  /api/v1/examples/ping:
    get:
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            type: string
        default:
          description: ""
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /api/v1/examples/post:
    post:
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/model.Account'
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/model.Account'
        default:
          description: ""
          schema:
            $ref: '#/definitions/chai.Error'
  /api/v1/examples/securities:
    get:
      description: custome header
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            type: string
        "400":
          description: ""
          schema:
            type: string
        "404":
          description: ""
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: custome header example
      tags:
      - example
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
